### ISSUE TITLE
shop (from polymer-cli v1.2) is not compatible with Edge

### ISSUE THREAD

**Issue by RuslanKim** [Polymer/shop#132]
![2017-06-14_11-36-24](https://user-images.githubusercontent.com/5648249/27115585-de1cd32a-50f5-11e7-8fb8-8fb1958d87e6.png)

Is there a fix?

**Comment by RuslanKim** [comment]
when "polymer serve" runs it works with IE11 but does not with latest Edge :(

**Comment by keanulee** [comment]
This seems to be an issue with Edge 15 which added support for CSS custom properties (the implementation has a bug - see https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12414257/).

This wasn't an issue before because we relied on the polyfill. We are currently considering whether to force the polyfill on Edge to workaround this issue.

**Comment by RuslanKim** [comment]
It makes sense, but Polymer website, which is build and based on Polymer too, works perfectly with Edge for some reason .)

**Comment by frankiefu** [comment]
Fixed in https://github.com/webcomponents/shadycss/pull/120

**Comment by RuslanKim** [comment]
Bad issues and bad practice, if you have to fix right now right here, just add these in landing html:

`<script>
        //Force all polyfills on for Edge 15
        if (window.navigator.userAgent.indexOf("Edge") > -1)
        {
            if (window.customElements) { window.customElements.forcePolyfill = true; }
            ShadyDOM = { force: true };
            ShadyCSS = { shimcssproperties: true };
        }
    </script>`
