### ISSUE TITLE
Is https://shop.polymer-project.org/ up to date?

### ISSUE THREAD

**Issue by SMEmp** [Polymer/shop#142]
It looks like https://shop.polymer-project.org/ is out of date to my untrained eye, due to the import of `polymer{,-mini,-micro}.html` instead of `polymer{,-element}.html`.

Since it's difficult to find examples that advertise the use of Web Components 1.0 or Polymer 2.0, it's unsettling that this one appears to be out of sync with the repository, and makes it all the more difficult to make the case to adopt Polymer 2.0.

I can (and likely will) setup my own server to test this out with, but there should definitely be a URL someone can visit to quickly see Web Components 1.0 working live.

**Comment by frankiefu** [comment]
Sorry about the delay. And as we are speaking we are working on getting the latest Shop deploy to the hosting server. We hit a few hiccups like getting differential serving working properly. Hopefully we will get that resolved soon. And with Polymer Summit coming soon that may contribute some delays. But we will try to get that asap. In the meantime please use this test server which should have up to date stuffs for testing:
https://shopping-5f1dc.firebaseapp.com/

**Comment by SMEmp** [comment]
Much appreciated, I understand how differential serving (http2 vs 1 I assume?) could be a pain to get right.
I definitely appreciate the temporary Firebase URL in the meantime.

**Comment by markovuksanovic** [comment]
I've also ran into this issue and it's been happening for a while. Not sure what the root cause is though. This may give some clues - if you run `Polymer.telemetry.registrations.forEach((reg) => console.log(reg.is))` in Firefox you will notice that iron-request is not registered at all and if you run the same command in chrome, iron-request shows up correctly. I'm not really sure why all the elements would register besides `iron-meta`.

Also there's an error in Firefox when you try loading. See screenshot below:
![image](https://user-images.githubusercontent.com/52777/30427416-1865349c-9993-11e7-982d-5242e49c7eb1.png)

**Comment by keanulee** [comment]
https://shop.polymer-project.org/ has now been updated to use Polymer 2 and [prpl-server-node](https://github.com/Polymer/prpl-server-node). The server configuration required to deploy to Google App Engine Flexible environment can be found in this branch: https://github.com/Polymer/shop/tree/app-engine-node
