### ISSUE TITLE
Whats about SEO?

### ISSUE THREAD

**Issue by ThinqDigital** [Polymer/shop#29]
http://webcache.googleusercontent.com/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=cache%3Ahttps%3A%2F%2Fshop.polymer-project.org&oq=cache%3Ahttps%3A%2F%2Fshop.polymer-project.org&rlz=1C1RAEH_deDE626DE648&aqs=chrome..69i57j69i58.1255j0j4

I Think it is bad for a Web-Shop.

**Comment by slifin** [comment]
Polymer looks great but it really does need server side rendering, the holes are too glaring in any JavaScript app that doesn't, it would really help compatibility with browsers, lynx, performance on first load, scraping, accessibility, screen readers etc 

Things like Google translate don't work: 
https://translate.google.co.uk/translate?sl=auto&tl=ar&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fshop.polymer-project.org%2F&edit-text= 

or the Internet Archive 
https://web.archive.org/web/20160523112309/http://shop.polymer-project.org/

At the moment the custom tags are like placeholder doms till polymer loads, maybe that could be changed so that content can be put in before via the server, then upgraded when the JavaScript loads, React does this with dom diffing maybe there's a more native way than just attaching ids to everything like react does..

**Comment by ebidel** [comment]
It looks like we could do a better job of updating the `<title>`, but Google has indexed this dynamic app just fine:

![screen shot 2016-05-23 at 2 25 47 pm](https://cloud.githubusercontent.com/assets/238208/15485152/83b9d204-20f2-11e6-847d-440dbcae1ffa.png)

The source doesn't have any of these details 😄 :

![screen shot 2016-05-23 at 2 33 29 pm](https://cloud.githubusercontent.com/assets/238208/15485305/5ce27928-20f3-11e6-8fac-6e8976e16ea8.png)

Other examples are the [Google I/O web app](https://www.google.com/?ion=1&espv=2#q=site%3Ahttps%3A%2F%2Fevents.google.com%2Fio2016%2F) and [Polymer's new site](https://www.google.com/#q=site%3Ahttps%3A%2F%2Fwww.polymer-project.org%2F1.0%2F&rct=j). Both of those are indexed.

The important bit is to follow the existing [web master guidelines](https://support.google.com/webmasters/answer/66359), and include things like canonical links, use `<a href>`, correct meta data, etc.

**Comment by frankiefu** [comment]
@blasten I think we can just update the document.title in `_onChangeSection`.

**Comment by abdonrd** [comment]
And what about things like Google Translate? As @slifin said.

**Comment by ebidel** [comment]
I ran the Google Translate chrome extension on pp.org:

![screen shot 2016-05-24 at 1 28 24 pm](https://cloud.githubusercontent.com/assets/238208/15518825/83966fb4-21b3-11e6-8ea5-fb349d6f3741.png)

Do other tools like internet archive work on today's existing SPAs? It's important to remember some of these tools were created a long time ago and may need updating.

**Comment by abdonrd** [comment]
@ebidel I'm not sure if all of them are SPA, but it works:
- https://angular.io
- https://hello-angularjs.appspot.com
- https://facebook.github.io/react/
- http://emberjs.com

**Comment by ebidel** [comment]
@abdonrd those are doc sites. I'd be more curious about apps built using those frameworks.

**Comment by CaptainCodeman** [comment]
@abdonrd most of the examples you give don't really use the frameworks they are advertising and are more static content than SPAs (ah, you posted the same while I was typing).

Using the "fetch as google" in webmaster tools is a good test as well - I've found polymer works well and renders the dynamically-loaded page content, Angular 2 has been hit and miss with which pieces are rendered.

**Comment by abdonrd** [comment]
@ebidel @CaptainCodeman Thanks guys!

**Comment by gedw99** [comment]
@ebidel 

 Could the shop demo then be updated with localisation (https://www.polymer-project.org/1.0/toolbox/localize). 

It would be a perfect example because you have everything in this demo:
- string
- pluralizations ( i doubt polymer localisation does that yet)
- datetime, numbers, currency (on the checkout page)

**Comment by gedw99** [comment]
sorry i did not realise this is closed. I will raise a NEW issue
