### ISSUE TITLE
Linting shows elements not defined

### ISSUE THREAD

**Issue by philipbeadle** [Polymer/shop#42]
I just ran polymer lint and get a heap of these
```
/src/shop-checkout.html:339:19
    <shop-select> is undefined.
/src/shop-checkout.html:354:21
    <shop-md-decorator> is undefined.
/src/shop-checkout.html:355:23
    <shop-underline> is undefined.
```

which is strange as the elements are defined and the linting seems to pick up only the last use of the element.  You can see this by looking at `/src/shop-checkout.html:339:19 <shop-select> is undefined`.

Any ideas on whats going on?

**Comment by keanulee** [comment]
(Lightly edited your issue for correct code formatting)

The reason for those errors is that `<shop-select/md-decorator/underline>` are not true custom elements, but instead are generic elements that we style using CSS (i.e. there are only styles and no actual declaration of `Polymer({ is: 'shop-select' })` in https://github.com/Polymer/shop/blob/master/src/shop-select.html). We did this because we only wanted to style the `<select>` element it wraps and didn't need any JavaScript logic for those elements.

**Comment by philipbeadle** [comment]
is there a way to not include these files in the linting process or do we have to specify al the fiels we want linted as part of the CI?

**Comment by frankiefu** [comment]
@philipbeadle I am not sure.  But I'd suggest asking the question over at the [polymer-cli](https://github.com/Polymer/polymer-cli/issues).
