### ISSUE TITLE
My custom element is not working in shop app, but working in polymer starter kit?

### ISSUE THREAD

**Issue by oneezy** [Polymer/shop#54]
I've created a custom "properties" grid system to use universally on any element. In every project thus far, I've had no problem using it...But when I try to use it in the shop-app, it doesn't work. Here's my custom property system that I'm importing in: https://github.com/oneezy/steel-properties

In Chrome dev tools network tab, it says that it's loading normally, however when I inspect an element it doesn't show up in the css and has no effect! It's got me scratching my head because it works completely fine w/ Polymer Starter Kit and in other projects...

I've included a short video showing my problem:
https://www.youtube.com/watch?v=tpyYxXTMdkU

Is there something I'm missing or doing wrong???

**Comment by keanulee** [comment]
Shop uses Shadow DOM by default (https://github.com/Polymer/shop/blob/master/index.html#L60) - does steel-properties support Shadow DOM style scoping? steel-properties CSS styles would need to be included inside each shadow root that is using it due to style encapsulation (See http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/, but don't use `/deep/` since it's deprecated).

**Comment by oneezy** [comment]
Thanks @keanulee, by changing `shadow` to `shady` in the shop app's `index.html` file, everything seems to work as expected:

---
```
        Polymer = {lazyRegister: true, dom: 'shadow'};

                becomes...

        Polymer = {lazyRegister: true, dom: 'shady'};
```
But what are the ramifications of this?

---

To answer your question about _Shadow DOM style scoping_, are you referring to the css custom styling variables and mixins? If you are, the answer is no (or not yet). 

[Steel-Properties](https://github.com/oneezy/steel-properties) is meant to be used as a "universal" way for initial layout so you can quickly use it on any element. When I include steel-properties into a file, it goes in and calls other files that have specific style properties written out, and you then can write these properties directly into your markup.

# For Example:

**HTML Markup:**
`<body mobile-bg="blue" tablet-bg="green" desktop-bg="yellow"></body>`

**Output:**
![image](https://cloud.githubusercontent.com/assets/7369575/16641173/b2c82f2a-43c3-11e6-93bd-5f4d65155b1d.png)

**The Code:**
![image](https://cloud.githubusercontent.com/assets/7369575/16641217/0e6d6ade-43c4-11e6-9cc7-1002bc46ed6b.png)


As you can see, `steel-properties` is not your typical `<custom-element>`. It's really just importing in style sheets with `[attribute="property"]`'s.

## So my questions now are:
- Should I be doing it this way or am I going about it wrong? 
- What would be the proper way to write my "steel-properties" so that it can work with both `shadow` and `shady` DOM universally?
- What are the ramifications of switching `shadow` to `shady` DOM in the shop app?
- What is the main reason for using `shadow` DOM instead of `shady` DOM in the shop app but not the Polymer Starter Kit? (performance?)

**Comment by keanulee** [comment]
Shadow DOM (with native style scoping) is the end goal, and shady DOM is just a necessary step there (it mimics tree scoping, but does not provide style scoping). For more information about shady DOM, see https://www.polymer-project.org/1.0/blog/shadydom. You should always try to support native shadow DOM (`dom: 'shadow'`).

Because styles are scoped to shadow roots, you would need to import the stylesheet inside each element. A good example is `iron-flex-layout-classes` (https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout-classes.html). You declare your styles inside a dom-module, and include it in the style for each element that uses these attributes:

iron-flex-layout-classes.html
```html
<dom-module id="iron-flex">
  <template>
    <style>
      /* Some styles */
    </style>
  </template>
</dom-module>
```

your-element.html
```html
<link rel="import" href="../iron-flex-layout/iron-flex-layout-classes.html">

<dom-module id="your-element">
  <template>
    <style include="iron-flex">
      /* Element styles */
    </style>
    <div class="layout horizontal layout-start"></div>
  </template>
  <script>...</script>
</dom-module>
```

**Comment by oneezy** [comment]
Got it. Thanks for the breakdown.
