### ISSUE TITLE
is it recommend to go with polyfill or shady dom ?

### ISSUE THREAD

**Issue by sowsan** [Polymer/shop#61]
While reading this article https://www.polymer-project.org/1.0/blog/shadydom, got confused the default templates that polymer gives and the reference application (shop app) implementation. In the templates and shop app , what I'm seeing is, its forcing to do use shadow dom by looking at the code in the index.html. So, what is the recommendation we need to follow for any new polymer applications ? do we need to use the below code as its or remove it to use the default shady dom ?

 Polymer = {lazyRegister: true, dom: 'shadow'};

    (function() {
      if ('registerElement' in document
          && 'import' in document.createElement('link')
          && 'content' in document.createElement('template')) {
        // platform is good!
      } else {
        // polyfill the platform!
        var e = document.createElement('script');
        e.src = '/bower_components/webcomponentsjs/webcomponents-lite.min.js';
        document.body.appendChild(e);
      }
    })();

**Comment by ebidel** [comment]
I prefer the above setup in my apps. In general, it's a good idea to:

1. lazy load the polyfills
2. use native shadow dom if its available. It's good for per and also helps you avoid gotchas in the future. You'll write code against the native implementation.
3. use the `lazyRegister` opt-in to reduce initial page load

We haven't made these the defaults yet because they're still new features (`lazyRegister`) or could possibly break existing apps if they weren't written properly to begin with (native SD). See https://github.com/Polymer/polymer/issues/1887 for enabling is by default.

**Comment by sowsan** [comment]
awesome thank you so much for the insights @ebidel :)
