### ISSUE TITLE
Add OpenGraph tags for each URL

### ISSUE THREAD

**Issue by tjsavage** [Polymer/shop#66]
Would be interesting to look into injecting OG tags for each page (including each product page). Having a pattern for this will make this a more realistic ecommerce site.

Goal would be to make the "Link Preview" look as complete as possible:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fshop.polymer-project.org%2Fdetail%2Fladies_outerwear%2FLadies%2BColorblock%2BWind%2BJacket

**Comment by tjsavage** [comment]
Similarly, even though search snippets do show structured data already, making sure the Structured Data Testing Tool picks up structured data:

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fshop.polymer-project.org%2Fdetail%2Fladies_outerwear%2FLadies%2BColorblock%2BWind%2BJacket

**Comment by minhlong139** [comment]
+1

**Comment by oneezy** [comment]
@CaptainCodeman has made some great efforts on this: 
https://github.com/CaptainCodeman/app-metadata

**Comment by CaptainCodeman** [comment]
Thanks @oneezy but I don't think it works for any system or tool that only looks at the index.html page (like the facebook og sharing debugger).  It works for Google's search bot which processes JS but it really needs some server-side templating to work for all.

So something more like https://github.com/CaptainCodeman/go-poly-tenant (which does some server-side changes to index.html for each request) ... happy to help add this if people are OK with it.

**Comment by CaptainCodeman** [comment]
I created a Go app to add the OpenGraph meta-tags (still using the existing index.html and json data files). You can see the results at:
https://shop-dot-captain-codeman.appspot.com/

Here's an [OpenGraph Debug result example](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fshop-dot-captain-codeman.appspot.com%2Fdetail%2Fladies_outerwear%2FLadies%2BColorblock%2BWind%2BJacket):

<img width="1037" alt="screen shot 2016-09-03 at 12 08 58 pm" src="https://cloud.githubusercontent.com/assets/304910/18226824/56f759fc-71cf-11e6-8f56-84eac105bade.png">

I'll tidy the code up and submit a PR in case anyone is interested.

**Comment by oneezy** [comment]
That's pretty slick @CaptainCodeman !  Your PR was amazingly right on time for me, as I'm just beginning to work on the SEO portion of my first polymer client project.

From my [Previous Research](https://docs.google.com/document/d/1uXh_4rkfeBIviBH3bU52_j38uNGYX7GzovfEhK4VX6Y/edit?usp=sharing) (I've done a LOT), I knew I could get away with a little bit of SEO tricks since Google is reading JS now, and I also knew that I was completely out of luck on the Social Meta/ OG Meta tags without utilizing a server for real page rendering.

(I'm completely frontend, so please excuse my lack of understanding when it comes to the backend)

-----

I'm currently hosting my website on Firebase and have my domain connected through with NameCheap. From lots of trial and error, I got it all working (thanks to this [SO Question](http://stackoverflow.com/questions/37874631/firebase-hosting-custom-domain-site-not-go-live-after-update-dns-records-by)).

- 1 `CNAME Record` (www)
- 2 `A Records` (ip addresses)
- 2 `TXT Records` (firebase verification)

-----

- **Firebase Hosting:** [sfi-feature.firebaseapp.com](sfi-feature.firebaseapp.com)
- **NameCheap Domain:** [sulphurfuelinjection.com](https://sulphurfuelinjection.com)

-----

Would I be able to set all this up through Firebase (BaaS - Backend as a Service)? 
Or would I have to move everything to Google App Engine (PaaS - Platform as a Service)?

I'm a bit confused on the best way of connecting all of these pieces together and this would be my first go at Go Lang.

Any pointers would be great! :smile:
Thank you for your contributions! :+1: 

![image](https://cloud.githubusercontent.com/assets/7369575/18257801/6498dba0-738f-11e6-8753-7b9ff250d41d.png)

**Comment by CaptainCodeman** [comment]
I'm not familiar enough with firebase to comment on what's possible from that side of things and couldn't find anything about the BaaS you mentioned from a cursory look around their site.

Whatever the language there would need to be some kind of server-side processing for it to work. If that isn't possible with firebase directly it would just be a case of splitting the domain used to serve the server-rendered frontend from the backend / database part (which from my understanding is what firebase 'is').

So yes, you could have the www. (or the naked domain) as the site that people see and use, running on appengine or some other dynamic hosting, with api. mapped to the firebase part for the client side to connect to (and probably the server-side as well so data is only in one place).

**Comment by abdonrd** [comment]
.

**Comment by abdonrd** [comment]
Any news about this?

**Comment by oneezy** [comment]
I'm curious also.

**Comment by Boscop** [comment]
Me too.

**Comment by oneezy** [comment]
The people have spoken! :laughing:

**Comment by gregroyal** [comment]
I'm interested also!

**Comment by keanulee** [comment]
Fixed by #144

**Comment by JaySunSyn** [comment]
I've made a tutorial on how to create dynamic OG-Tags with Firebase hosting.
https://medium.com/@jalalio/dynamic-og-tags-in-your-statically-firebase-hosted-polymer-app-476f18428b8b
