### ISSUE TITLE
shop-category-data dynamic load via ajax calling

### ISSUE THREAD

**Issue by sidealice** [Polymer/shop#88]
I try to let property **categories** loaded via AJAX in file shop-category-data.html.

It seems rendered correct data in homepage, but when i click either category from homepage it gave me 404 error.

My modification is:
		<iron-ajax 
			id="categorydata"  
			url="/api/categories.php"  
			handle-as="json" 
			on-response="_loadCategorydata"  >
		</iron-ajax> 

      _loadCategorydata: function(data) { 
        this.categories = data.detail.response;
      }, 

I guess the reason is AJAX is ASYNC, how can I bind the data with callback? Thanks!

**Comment by keanulee** [comment]
Hi @sidealice. In Shop, all instances of `<shop-category-data>` share the same same `categories` array (that is, a modification to _subproperties_ of `this.categories` by one instance will be reflected in all other instances). In your example, you changed `this.categories` to reference a completely different object, and this change won't be reflected in the other instances of `<shop-category-data>` (e.g. the instance in the product list page).

To fix this, you could modify `this.categories` in place instead of replacing it (e.g. push each category to the existing array - `data.detail.response.forEach(category => this.push('categories', category));`

**Comment by sidealice** [comment]
Hi @keanulee ,thanks for your help.

But after I modify the code, when entered specific category I got the following error:
polymer-mini.html:2044 Uncaught TypeError: Cannot read property 'name' of null

Tracing the code to shop-list:182, I found out that category is null.
```
  _categoryChanged: function(category, visible) {
	console.log('shop-list _categoryChanged');
	console.log(category);
	if (visible) {
	  this.debounce('change-section', function() {
		// Notify the category and the page's title
		this.fire('change-section', {
		  category: category.name,
		  title: category.title
		});
	  });
	}
  },
```

I guess still the category-data page's problem,In shop-category-data.html file what I did:
```
	<template>
		<iron-ajax
			verbose 
			auto  
			loading="{{isloading}}"
			url="/api/categories.json" 
			method="GET"
			handle-as="json" 
			on-response="getCategoryData" 
			debounce-duration="300" 
			id="requestGetCategoryData">
		</iron-ajax>
	</template>

  <script>
  (function() {
	categoryList=[];

    Polymer({
      properties: {
        categories: {
          type: Array,
          value: categoryList,
          //readOnly: true,
          notify: true
        },
      getCategoryData: function(data) {
        console.log('call back getCategoryData');
        console.log(data.detail.response);
	data.detail.response.forEach(category => this.push('categories', category));
      }
```

**Comment by keanulee** [comment]
Seems like you need to add a check if category is `null`. In our version (without XHR), the selected `category` always has a name, but in your case (where it is defined only after XHR response), it may not initially have a name.

**Comment by sidealice** [comment]
Thanks a lot!

With your help I find out the problem was caused by `category.name`'s type should be String.
I set it as integer before.
